### PR TITLE
Prohibit throwing Error in generateTests and check

### LINKED ISSUE #32: Prohibit using Asserts in tests
Need to catch `AssertionError` in `solve` method and raise `Fatal error`

### PR DESCRIPTION
**Pull request by SerVB**
This resolves #32.

### CODE REVIEW

**Comment by aaaaaa2493** [comment]
Why there are commits that were already merged? Update your fork and let me see actual changes

**Comment by SerVB** [comment]
Yeah, working on it. Marked as WIP, by the way ;)

**Comment by SerVB** [comment]
Please take a look.

**Comment by aaaaaa2493** [comment]
Oh, I mistyped the issue description - I meant in `check` method, not `solve`. Because some external test writers use Assert instead of returning `CheckResult` and that is bad. So any `AssertionError` produced in `check` should be handled as `Fatal error in test #N` like any exception that is thrown during checking.

There can't be `AssertionError` in `solve` method simply because a method called using reflection and if there are any `Throwable` while running this method then `InvocationTargetException` would be raised (but I'm not 100% sure, it may be true only for `Exception` bit not for `Error` and you can try it).

Oh, now I noticed that I talked about `run` method above but not `solve` :) Still, I have plans to remove `solve`, `checkSolved`, `generatePredefinedInputOutput` for a better design. 

Guess, the issue is transposed to be named `Prohibit throwing Error in generateTests and check`

**Comment by aaaaaa2493** [comment]
And also, keep in mind that `Fatal error` should be generated here, in a single place (there is a uniform way of feedback with report and stacktrace, not just `Fatal error` like in your solution)
https://github.com/hyperskill/hs-test/blob/dev/src/main/java/org/hyperskill/hstest/dev/exception/FailureHandler.java#L203

**Comment by SerVB** [comment]
Replaced by #39.

**Pull request closed without merging**
